### ISSUE TITLE
No exception handling for users without sudo

### ISSUE THREAD

**Issue by jesmith** [Critical-Start/FallofSudo#1]
Something like this should help:
#somewhere around line 330

    def sudofile():

        # File to save sudo rules output
        fname = "Output/sudorules.txt"
        f = open(fname, "w+")

        # run the sudo -ll command
        while True:
            try:
                sudoll = subprocess.check_output(['sudo' , '-ll'])
            except Exception as check_output_err:
                print "You may not be a sudoer"
                sys.exit(1)

        # Saving sudoll output to file
        f.write(sudoll)
        f.close

**Comment by jesmith** [comment]
If RunAsGroups option is not set in sudoers file it causes a crash

    for item in sudooutput:
        print OKGREEN + "\n[!] RunAsUsers: " + ENDC + item[0]
        if item[1] != None:
            print OKGREEN + "[!] RunAsGroups: " + ENDC + item[1]
        if item[2] != None:
            print OKGREEN + "[!] Options: " + ENDC + item[2]
        print OKGREEN + "[!] Commands: " + ENDC + item[3]

    return sudooutput

**Comment by paragonsec** [comment]
Added the following:

```# Saving sudo rules to a csv file for easy parsing
def sudofile():

    # File to save sudo rules output
    fname = "Output/sudorules.txt"
    f = open(fname, "w+")

    # run the sudo -ll command
    # Update suggested by jesmith
    while True:
        try:
            sudoll = subprocess.check_output(['sudo' , '-ll'])
        except Exception as check_output_err:
            sys.exit(1)

    sudoll = subprocess.check_output(['sudo' , '-ll'])

    # Saving sudoll output to file
    f.write(sudoll)
    f.close
```
Removed the print statement as the output of `sudo -ll` is already verbose enough to explain the issue.

**Comment by paragonsec** [comment]
Actually. Had to change it to this.

```
    try:
	sudoll = subprocess.check_output(['sudo' , '-ll'])
    except subprocess.CalledProcessError as e:
        print e.output
	sys.exit(1)
```
