### ISSUE TITLE
If RunAsGroups is not defined in sudoers file it causes a crash

### ISSUE THREAD

**Issue by jesmith** [Critical-Start/FallofSudo#2]
for item in sudooutput:
        print OKGREEN + "\n[!] RunAsUsers: " + ENDC + item[0]
        if item[1] != None:
            print OKGREEN + "[!] RunAsGroups: " + ENDC + item[1]
        if item[2] != None:
            print OKGREEN + "[!] Options: " + ENDC + item[2]
        print OKGREEN + "[!] Commands: " + ENDC + item[3]

    return sudooutput

**Comment by paragonsec** [comment]
Updated the source. Closing this issue. Thanks for the feedback!
